[uwsgi]
plugin = python3
chdir = /var/www/framesv/
module = app
master = true
protocol = uwsgi
processes = 2
;max-requests = 1500
threads = 2
harakiri = 30
reload-on-rss = 512
min-worker-lifetime = 10

single-interpreter = true
no-orphans = true
log-date = true
env = BASE_PATH=/storage/storage/sframes/
