# See rsyncd.conf man page for more options.

uid = lsync
gid = lsync
use chroot = yes
max connections = 4
pid file = /var/run/rsyncd.pid
exclude = lost+found/
transfer logging = yes
timeout = 120
# ignore nonreadable = yes
dont compress   = *.gz *.tgz *.zip *.z *.Z *.rpm *.deb *.bz2 *.xz *.zst *.7z *.jpg *.png *.webp *.mkv
address = 127.0.0.1
port = 1873
reverse lookup = no
forward lookup = no

[storage]
path = /storage/storage
max connections = 3
log file = /var/log/rsyncd.log
#write only = yes
open noatime = yes
uid = lsync
gid = lsync
auth users = lsync
secrets file = /etc/rsyncd.secrets
read only = no
# refuse options =
