settings {
	logfile = "/var/log/lsyncd.log",
	statusFile = "/var/log/lsyncd-status.log",
	statusInterval = 20,
	maxDelays = 30
}
sync {
	default.rsync,
	delay = 5,
	source = "/storage/storage/",
	target = "rsync://lsync@127.0.0.1:1873/storage/",
	init = false,
	rsync = {
		compress = false,
		perms = false,
		times = false,
		hard_links = true,
		_extra = {"--password-file=/etc/lsyncd/lsync.pwd", "--chmod=a+r"}
	}
}
