# needs to be set manually
#ssl_certificate /etc/letsencrypt/live/$host/fullchain.pem;
#ssl_certificate_key /etc/letsencrypt/live/$host/privkey.pem;
ssl_dhparam /etc/ssl/anito/dhparams.pem;
ssl_session_timeout 4h;
ssl_session_cache shared:nginxSSL:10m;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
ssl_ciphers HIGH:!AES256:!ARIA:!CAMELLIA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK;
# requires nginx 1.19.4 - sets TLS1.3 ciphers
#ssl_conf_command Ciphersuites TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256;
ssl_prefer_server_ciphers on;
ssl_buffer_size 4k;
ssl_session_tickets off;
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
add_header X-Content-Type-Options "nosniff" always;

ssl_stapling on;
ssl_stapling_verify on;
resolver 8.8.8.8 8.8.4.4 valid=300s;
resolver_timeout 8s;
